<?php
/**
 * Export to PHP Array plugin for PHPMyAdmin
 * @version 0.2b
 */

//
// Database "mckansys"
//

// mckansys.ADMIN
$ADMIN = array(
  array('ID'=>'1','NAME'=>'test','EMAIL'=>'a@a.com','PASSWORD'=>'77de54ccf56eb6f7dbf99e4d3be949ab6f9b0a55df8ac28564cb9f63a10be8af6ab3f7c2','DATE'=>'2013-10-02 00:00:00'),
  array('ID'=>'2','NAME'=>'b','EMAIL'=>'b@b.com','PASSWORD'=>'7014de06693eca5c7a6f258b98fa2048ef7ad6c1faf1e46a706cd0615ada442bbc570b0e','DATE'=>'2013-10-02 00:00:00')
);

// mckansys.ASIAN_COUNTRY
$ASIAN_COUNTRY = array(
  array('ID'=>'1','NAME'=>'Brunei Darussalam','CAPITAL'=>'Bandar Seri Begawan','LANGUAGE'=>'Malay, English','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'B$ (Brunei Dollar)','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'brunei.jpg'),
  array('ID'=>'2','NAME'=>'Cambodia','CAPITAL'=>'Phnom Penh','LANGUAGE'=>'Khmer','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'Riel','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'cambodia.jpg'),
  array('ID'=>'3','NAME'=>'Indonesia','CAPITAL'=>'Jakarta','LANGUAGE'=>'Indonesian','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'Rupiah','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'indonesia.jpg'),
  array('ID'=>'4','NAME'=>'Lao PDR','CAPITAL'=>'Vientiane','LANGUAGE'=>'Lao','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'Kip','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'lao.jpg'),
  array('ID'=>'5','NAME'=>'Malaysia','CAPITAL'=>'Kuala Lumpur','LANGUAGE'=>'Malay, English, Chinese, Tamil','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'Ringgit','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'malaysia.jpg'),
  array('ID'=>'6','NAME'=>'Myanmar','CAPITAL'=>'Nay Pyi Taw','LANGUAGE'=>'Myanmar','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'Kyat','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'myanmar.jpg'),
  array('ID'=>'7','NAME'=>'Philippines','CAPITAL'=>'Manila','LANGUAGE'=>'Filipino, English, Spanish','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'Peso','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'philipine.jpg'),
  array('ID'=>'8','NAME'=>'Singapore','CAPITAL'=>'Singapore','LANGUAGE'=>'English, Malay, Mandarin, Tamil','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'S$ (Singapore Dollar)','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'singapore.jpg'),
  array('ID'=>'9','NAME'=>'Thailand','CAPITAL'=>'Bangkok','LANGUAGE'=>'Thai','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'Baht','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'thailand.jpg'),
  array('ID'=>'10','NAME'=>'Viet Nam','CAPITAL'=>'Ha Noi','LANGUAGE'=>'Vietnamese','POPULATION'=>'','RELIGION'=>'','CURRENCY'=>'Dong','PARAGRAPH_1'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PARAGRAPH_2'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum.','PARAGRAPH_3'=>'Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry\'s standard dummy text ever since the 1500s','PHOTO_NAME'=>'vietnam.jpg')
);

// mckansys.COUNTRY
$COUNTRY = array(
  array('ID'=>'1','NAME'=>'Afghanistan'),
  array('ID'=>'2','NAME'=>'Albania'),
  array('ID'=>'3','NAME'=>'Algeria'),
  array('ID'=>'4','NAME'=>'American Samoa'),
  array('ID'=>'5','NAME'=>'Andorra'),
  array('ID'=>'6','NAME'=>'Angola'),
  array('ID'=>'7','NAME'=>'Anguilla'),
  array('ID'=>'8','NAME'=>'Antarctica'),
  array('ID'=>'9','NAME'=>'Antigua and Barbuda'),
  array('ID'=>'10','NAME'=>'Argentina'),
  array('ID'=>'11','NAME'=>'Armenia'),
  array('ID'=>'12','NAME'=>'Armenia'),
  array('ID'=>'13','NAME'=>'Aruba'),
  array('ID'=>'14','NAME'=>'Australia'),
  array('ID'=>'15','NAME'=>'Austria'),
  array('ID'=>'16','NAME'=>'Azerbaijan'),
  array('ID'=>'17','NAME'=>'Azerbaijan'),
  array('ID'=>'18','NAME'=>'Bahamas'),
  array('ID'=>'19','NAME'=>'Bahrain'),
  array('ID'=>'20','NAME'=>'Bangladesh'),
  array('ID'=>'21','NAME'=>'Barbados'),
  array('ID'=>'22','NAME'=>'Belarus'),
  array('ID'=>'23','NAME'=>'Belgium'),
  array('ID'=>'24','NAME'=>'Belize'),
  array('ID'=>'25','NAME'=>'Benin'),
  array('ID'=>'26','NAME'=>'Bermuda'),
  array('ID'=>'27','NAME'=>'Bhutan'),
  array('ID'=>'28','NAME'=>'Bolivia'),
  array('ID'=>'29','NAME'=>'Bosnia and Herzegovina'),
  array('ID'=>'30','NAME'=>'Botswana'),
  array('ID'=>'31','NAME'=>'Bouvet Island'),
  array('ID'=>'32','NAME'=>'Brazil'),
  array('ID'=>'33','NAME'=>'British Indian Ocean Territory'),
  array('ID'=>'34','NAME'=>'Brunei Darussalam'),
  array('ID'=>'35','NAME'=>'Bulgaria'),
  array('ID'=>'36','NAME'=>'Burkina Faso'),
  array('ID'=>'37','NAME'=>'Burundi'),
  array('ID'=>'38','NAME'=>'Cambodia'),
  array('ID'=>'39','NAME'=>'Cameroon'),
  array('ID'=>'40','NAME'=>'Canada'),
  array('ID'=>'41','NAME'=>'Cape Verde'),
  array('ID'=>'42','NAME'=>'Cayman Islands'),
  array('ID'=>'43','NAME'=>'Central African Republic'),
  array('ID'=>'44','NAME'=>'Chad'),
  array('ID'=>'45','NAME'=>'Chile'),
  array('ID'=>'46','NAME'=>'China'),
  array('ID'=>'47','NAME'=>'Christmas Island'),
  array('ID'=>'48','NAME'=>'Cocos (Keeling) Islands'),
  array('ID'=>'49','NAME'=>'Colombia'),
  array('ID'=>'50','NAME'=>'Comoros'),
  array('ID'=>'51','NAME'=>'Congo'),
  array('ID'=>'52','NAME'=>'Congo, The Democratic Republic of The'),
  array('ID'=>'53','NAME'=>'Cook Islands'),
  array('ID'=>'54','NAME'=>'Costa Rica'),
  array('ID'=>'55','NAME'=>'Cote D\'ivoire'),
  array('ID'=>'56','NAME'=>'Croatia'),
  array('ID'=>'57','NAME'=>'Cuba'),
  array('ID'=>'58','NAME'=>'Cyprus'),
  array('ID'=>'60','NAME'=>'Czech Republic'),
  array('ID'=>'61','NAME'=>'Denmark'),
  array('ID'=>'62','NAME'=>'Djibouti'),
  array('ID'=>'63','NAME'=>'Dominica'),
  array('ID'=>'64','NAME'=>'Dominican Republic'),
  array('ID'=>'65','NAME'=>'Easter Island'),
  array('ID'=>'66','NAME'=>'Ecuador'),
  array('ID'=>'67','NAME'=>'Egypt'),
  array('ID'=>'68','NAME'=>'El Salvador'),
  array('ID'=>'69','NAME'=>'Equatorial Guinea'),
  array('ID'=>'70','NAME'=>'Eritrea'),
  array('ID'=>'71','NAME'=>'Estonia'),
  array('ID'=>'72','NAME'=>'Ethiopia'),
  array('ID'=>'73','NAME'=>'Falkland Islands (Malvinas)'),
  array('ID'=>'74','NAME'=>'Faroe Islands'),
  array('ID'=>'75','NAME'=>'Fiji'),
  array('ID'=>'76','NAME'=>'Finland'),
  array('ID'=>'77','NAME'=>'France'),
  array('ID'=>'78','NAME'=>'French Guiana'),
  array('ID'=>'79','NAME'=>'French Polynesia'),
  array('ID'=>'80','NAME'=>'French Southern Territories'),
  array('ID'=>'81','NAME'=>'Gabon'),
  array('ID'=>'82','NAME'=>'Gambia'),
  array('ID'=>'83','NAME'=>'Georgia'),
  array('ID'=>'85','NAME'=>'Germany'),
  array('ID'=>'86','NAME'=>'Ghana'),
  array('ID'=>'87','NAME'=>'Gibraltar'),
  array('ID'=>'88','NAME'=>'Greece'),
  array('ID'=>'89','NAME'=>'Greenland'),
  array('ID'=>'91','NAME'=>'Grenada'),
  array('ID'=>'92','NAME'=>'Guadeloupe'),
  array('ID'=>'93','NAME'=>'Guam'),
  array('ID'=>'94','NAME'=>'Guatemala'),
  array('ID'=>'95','NAME'=>'Guinea'),
  array('ID'=>'96','NAME'=>'Guinea-bissau'),
  array('ID'=>'97','NAME'=>'Guyana'),
  array('ID'=>'98','NAME'=>'Haiti'),
  array('ID'=>'99','NAME'=>'Heard Island and Mcdonald Islands'),
  array('ID'=>'100','NAME'=>'Honduras'),
  array('ID'=>'101','NAME'=>'Hong Kong'),
  array('ID'=>'102','NAME'=>'Hungary'),
  array('ID'=>'103','NAME'=>'Iceland'),
  array('ID'=>'104','NAME'=>'India'),
  array('ID'=>'105','NAME'=>'Indonesia'),
  array('ID'=>'106','NAME'=>'Indonesia'),
  array('ID'=>'107','NAME'=>'Iran'),
  array('ID'=>'108','NAME'=>'Iraq'),
  array('ID'=>'109','NAME'=>'Ireland'),
  array('ID'=>'110','NAME'=>'Israel'),
  array('ID'=>'111','NAME'=>'Italy'),
  array('ID'=>'112','NAME'=>'Jamaica'),
  array('ID'=>'113','NAME'=>'Japan'),
  array('ID'=>'114','NAME'=>'Jordan'),
  array('ID'=>'115','NAME'=>'Kazakhstan'),
  array('ID'=>'116','NAME'=>'Kazakhstan'),
  array('ID'=>'117','NAME'=>'Kenya'),
  array('ID'=>'118','NAME'=>'Kiribati'),
  array('ID'=>'119','NAME'=>'Korea, North'),
  array('ID'=>'120','NAME'=>'Korea, South'),
  array('ID'=>'121','NAME'=>'Kosovo'),
  array('ID'=>'122','NAME'=>'Kuwait'),
  array('ID'=>'123','NAME'=>'Kyrgyzstan'),
  array('ID'=>'124','NAME'=>'Laos'),
  array('ID'=>'125','NAME'=>'Latvia'),
  array('ID'=>'126','NAME'=>'Lebanon'),
  array('ID'=>'127','NAME'=>'Lesotho'),
  array('ID'=>'128','NAME'=>'Liberia'),
  array('ID'=>'129','NAME'=>'Libyan Arab Jamahiriya'),
  array('ID'=>'130','NAME'=>'Liechtenstein'),
  array('ID'=>'131','NAME'=>'Lithuania'),
  array('ID'=>'132','NAME'=>'Luxembourg'),
  array('ID'=>'133','NAME'=>'Macau'),
  array('ID'=>'134','NAME'=>'Macedonia'),
  array('ID'=>'135','NAME'=>'Madagascar'),
  array('ID'=>'136','NAME'=>'Malawi'),
  array('ID'=>'137','NAME'=>'Malaysia'),
  array('ID'=>'138','NAME'=>'Maldives'),
  array('ID'=>'139','NAME'=>'Mali'),
  array('ID'=>'140','NAME'=>'Malta'),
  array('ID'=>'141','NAME'=>'Marshall Islands'),
  array('ID'=>'142','NAME'=>'Martinique'),
  array('ID'=>'143','NAME'=>'Mauritania'),
  array('ID'=>'144','NAME'=>'Mauritius'),
  array('ID'=>'145','NAME'=>'Mayotte'),
  array('ID'=>'146','NAME'=>'Mexico'),
  array('ID'=>'147','NAME'=>'Micronesia, Federated States of'),
  array('ID'=>'148','NAME'=>'Moldova, Republic of'),
  array('ID'=>'149','NAME'=>'Monaco'),
  array('ID'=>'150','NAME'=>'Mongolia'),
  array('ID'=>'151','NAME'=>'Montenegro'),
  array('ID'=>'152','NAME'=>'Montserrat'),
  array('ID'=>'153','NAME'=>'Morocco'),
  array('ID'=>'154','NAME'=>'Mozambique'),
  array('ID'=>'155','NAME'=>'Myanmar'),
  array('ID'=>'156','NAME'=>'Namibia'),
  array('ID'=>'157','NAME'=>'Nauru'),
  array('ID'=>'158','NAME'=>'Nepal'),
  array('ID'=>'159','NAME'=>'Netherlands'),
  array('ID'=>'160','NAME'=>'Netherlands Antilles'),
  array('ID'=>'161','NAME'=>'New Caledonia'),
  array('ID'=>'162','NAME'=>'New Zealand'),
  array('ID'=>'163','NAME'=>'Nicaragua'),
  array('ID'=>'164','NAME'=>'Niger'),
  array('ID'=>'165','NAME'=>'Nigeria'),
  array('ID'=>'166','NAME'=>'Niue'),
  array('ID'=>'167','NAME'=>'Norfolk Island'),
  array('ID'=>'168','NAME'=>'Northern Mariana Islands'),
  array('ID'=>'169','NAME'=>'Norway'),
  array('ID'=>'170','NAME'=>'Oman'),
  array('ID'=>'171','NAME'=>'Pakistan'),
  array('ID'=>'172','NAME'=>'Palau'),
  array('ID'=>'173','NAME'=>'Palestinian Territory'),
  array('ID'=>'174','NAME'=>'Panama'),
  array('ID'=>'175','NAME'=>'Papua New Guinea'),
  array('ID'=>'176','NAME'=>'Paraguay'),
  array('ID'=>'177','NAME'=>'Peru'),
  array('ID'=>'178','NAME'=>'Philippines'),
  array('ID'=>'179','NAME'=>'Pitcairn'),
  array('ID'=>'180','NAME'=>'Poland'),
  array('ID'=>'181','NAME'=>'Portugal'),
  array('ID'=>'182','NAME'=>'Puerto Rico'),
  array('ID'=>'183','NAME'=>'Qatar'),
  array('ID'=>'184','NAME'=>'Reunion'),
  array('ID'=>'185','NAME'=>'Romania'),
  array('ID'=>'186','NAME'=>'Russia'),
  array('ID'=>'187','NAME'=>'Russia'),
  array('ID'=>'188','NAME'=>'Rwanda'),
  array('ID'=>'189','NAME'=>'Saint Helena'),
  array('ID'=>'190','NAME'=>'Saint Kitts and Nevis'),
  array('ID'=>'191','NAME'=>'Saint Lucia'),
  array('ID'=>'192','NAME'=>'Saint Pierre and Miquelon'),
  array('ID'=>'193','NAME'=>'Saint Vincent and The Grenadines'),
  array('ID'=>'194','NAME'=>'Samoa'),
  array('ID'=>'195','NAME'=>'San Marino'),
  array('ID'=>'196','NAME'=>'Sao Tome and Principe'),
  array('ID'=>'197','NAME'=>'Saudi Arabia'),
  array('ID'=>'198','NAME'=>'Senegal'),
  array('ID'=>'199','NAME'=>'Serbia and Montenegro'),
  array('ID'=>'200','NAME'=>'Seychelles'),
  array('ID'=>'201','NAME'=>'Sierra Leone'),
  array('ID'=>'202','NAME'=>'Singapore'),
  array('ID'=>'203','NAME'=>'Slovakia'),
  array('ID'=>'204','NAME'=>'Slovenia'),
  array('ID'=>'205','NAME'=>'Solomon Islands'),
  array('ID'=>'206','NAME'=>'Somalia'),
  array('ID'=>'207','NAME'=>'South Africa'),
  array('ID'=>'208','NAME'=>'South Georgia and The South Sandwich Islands'),
  array('ID'=>'209','NAME'=>'Spain'),
  array('ID'=>'210','NAME'=>'Sri Lanka'),
  array('ID'=>'211','NAME'=>'Sudan'),
  array('ID'=>'212','NAME'=>'Suriname'),
  array('ID'=>'213','NAME'=>'Svalbard and Jan Mayen'),
  array('ID'=>'214','NAME'=>'Swaziland'),
  array('ID'=>'215','NAME'=>'Sweden'),
  array('ID'=>'216','NAME'=>'Switzerland'),
  array('ID'=>'217','NAME'=>'Syria'),
  array('ID'=>'218','NAME'=>'Taiwan'),
  array('ID'=>'219','NAME'=>'Tajikistan'),
  array('ID'=>'220','NAME'=>'Tanzania, United Republic of'),
  array('ID'=>'221','NAME'=>'Thailand'),
  array('ID'=>'222','NAME'=>'Timor-leste'),
  array('ID'=>'223','NAME'=>'Togo'),
  array('ID'=>'224','NAME'=>'Tokelau'),
  array('ID'=>'225','NAME'=>'Tonga'),
  array('ID'=>'226','NAME'=>'Trinidad and Tobago'),
  array('ID'=>'227','NAME'=>'Tunisia'),
  array('ID'=>'228','NAME'=>'Turkey'),
  array('ID'=>'229','NAME'=>'Turkey'),
  array('ID'=>'230','NAME'=>'Turkmenistan'),
  array('ID'=>'231','NAME'=>'Turks and Caicos Islands'),
  array('ID'=>'232','NAME'=>'Tuvalu'),
  array('ID'=>'233','NAME'=>'Uganda'),
  array('ID'=>'234','NAME'=>'Ukraine'),
  array('ID'=>'235','NAME'=>'United Arab Emirates'),
  array('ID'=>'236','NAME'=>'United Kingdom'),
  array('ID'=>'237','NAME'=>'United States'),
  array('ID'=>'238','NAME'=>'United States Minor Outlying Islands'),
  array('ID'=>'239','NAME'=>'Uruguay'),
  array('ID'=>'240','NAME'=>'Uzbekistan'),
  array('ID'=>'241','NAME'=>'Vanuatu'),
  array('ID'=>'242','NAME'=>'Vatican City'),
  array('ID'=>'243','NAME'=>'Venezuela'),
  array('ID'=>'244','NAME'=>'Vietnam'),
  array('ID'=>'245','NAME'=>'Virgin Islands, British'),
  array('ID'=>'246','NAME'=>'Virgin Islands, U.S.'),
  array('ID'=>'247','NAME'=>'Wallis and Futuna'),
  array('ID'=>'248','NAME'=>'Western Sahara'),
  array('ID'=>'249','NAME'=>'Yemen'),
  array('ID'=>'250','NAME'=>'Yemen'),
  array('ID'=>'251','NAME'=>'Zambia'),
  array('ID'=>'252','NAME'=>'Zimbabwe')
);

// mckansys.DEPARTMENT
$DEPARTMENT = array(
  array('ID'=>'1','NAME'=>'A')
);

// mckansys.DOWNLOAD_STATISTICS
$DOWNLOAD_STATISTICS = array(
  array('ID'=>'1','USER_ID'=>'1','PDF_ID'=>'41','DOWNLOAD_DATETIME'=>'2013-12-31 05:26:28'),
  array('ID'=>'2','USER_ID'=>'1','PDF_ID'=>'30','DOWNLOAD_DATETIME'=>'2014-01-04 21:45:53'),
  array('ID'=>'3','USER_ID'=>'1','PDF_ID'=>'42','DOWNLOAD_DATETIME'=>'2014-01-04 22:24:10'),
  array('ID'=>'4','USER_ID'=>'1','PDF_ID'=>'30','DOWNLOAD_DATETIME'=>'2014-01-04 22:42:08'),
  array('ID'=>'5','USER_ID'=>'1','PDF_ID'=>'31','DOWNLOAD_DATETIME'=>'2014-01-05 07:01:36'),
  array('ID'=>'6','USER_ID'=>'1','PDF_ID'=>'32','DOWNLOAD_DATETIME'=>'2014-01-05 07:01:53'),
  array('ID'=>'7','USER_ID'=>'1','PDF_ID'=>'33','DOWNLOAD_DATETIME'=>'2014-01-05 07:02:03'),
  array('ID'=>'8','USER_ID'=>'1','PDF_ID'=>'34','DOWNLOAD_DATETIME'=>'2014-01-05 07:02:12'),
  array('ID'=>'9','USER_ID'=>'1','PDF_ID'=>'36','DOWNLOAD_DATETIME'=>'2014-01-05 07:02:28'),
  array('ID'=>'10','USER_ID'=>'1','PDF_ID'=>'37','DOWNLOAD_DATETIME'=>'2014-01-05 07:02:39'),
  array('ID'=>'11','USER_ID'=>'7','PDF_ID'=>'42','DOWNLOAD_DATETIME'=>'2014-01-06 10:35:17'),
  array('ID'=>'12','USER_ID'=>'14','PDF_ID'=>'23','DOWNLOAD_DATETIME'=>'2014-01-06 12:00:31'),
  array('ID'=>'13','USER_ID'=>'13','PDF_ID'=>'39','DOWNLOAD_DATETIME'=>'2014-01-06 14:45:27'),
  array('ID'=>'14','USER_ID'=>'13','PDF_ID'=>'26','DOWNLOAD_DATETIME'=>'2014-01-06 14:46:06'),
  array('ID'=>'15','USER_ID'=>'10','PDF_ID'=>'29','DOWNLOAD_DATETIME'=>'2014-01-06 17:12:17'),
  array('ID'=>'16','USER_ID'=>'7','PDF_ID'=>'27','DOWNLOAD_DATETIME'=>'2014-01-06 17:19:37'),
  array('ID'=>'17','USER_ID'=>'7','PDF_ID'=>'25','DOWNLOAD_DATETIME'=>'2014-01-06 17:20:15'),
  array('ID'=>'18','USER_ID'=>'7','PDF_ID'=>'38','DOWNLOAD_DATETIME'=>'2014-01-06 17:21:09'),
  array('ID'=>'19','USER_ID'=>'7','PDF_ID'=>'30','DOWNLOAD_DATETIME'=>'2014-01-06 17:26:11'),
  array('ID'=>'20','USER_ID'=>'7','PDF_ID'=>'31','DOWNLOAD_DATETIME'=>'2014-01-06 17:27:51'),
  array('ID'=>'21','USER_ID'=>'13','PDF_ID'=>'23','DOWNLOAD_DATETIME'=>'2014-01-15 08:19:40'),
  array('ID'=>'22','USER_ID'=>'7','PDF_ID'=>'32','DOWNLOAD_DATETIME'=>'2014-01-22 15:35:47'),
  array('ID'=>'23','USER_ID'=>'7','PDF_ID'=>'36','DOWNLOAD_DATETIME'=>'2014-01-22 16:10:19'),
  array('ID'=>'24','USER_ID'=>'1','PDF_ID'=>'32','DOWNLOAD_DATETIME'=>'2014-01-24 15:11:29'),
  array('ID'=>'25','USER_ID'=>'1','PDF_ID'=>'36','DOWNLOAD_DATETIME'=>'2014-01-24 15:12:47'),
  array('ID'=>'26','USER_ID'=>'1','PDF_ID'=>'36','DOWNLOAD_DATETIME'=>'2014-01-24 15:15:43'),
  array('ID'=>'27','USER_ID'=>'7','PDF_ID'=>'23','DOWNLOAD_DATETIME'=>'2014-02-10 15:04:08'),
  array('ID'=>'28','USER_ID'=>'7','PDF_ID'=>'46','DOWNLOAD_DATETIME'=>'2014-02-10 15:07:53'),
  array('ID'=>'29','USER_ID'=>'7','PDF_ID'=>'26','DOWNLOAD_DATETIME'=>'2014-02-10 15:10:30'),
  array('ID'=>'30','USER_ID'=>'7','PDF_ID'=>'43','DOWNLOAD_DATETIME'=>'2014-02-10 15:12:11'),
  array('ID'=>'31','USER_ID'=>'7','PDF_ID'=>'27','DOWNLOAD_DATETIME'=>'2014-02-10 15:12:54'),
  array('ID'=>'32','USER_ID'=>'7','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-10 15:16:50'),
  array('ID'=>'33','USER_ID'=>'7','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-10 15:17:01'),
  array('ID'=>'34','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:18'),
  array('ID'=>'35','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:21'),
  array('ID'=>'36','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:23'),
  array('ID'=>'37','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:24'),
  array('ID'=>'38','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:25'),
  array('ID'=>'39','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:27'),
  array('ID'=>'40','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:28'),
  array('ID'=>'41','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:29'),
  array('ID'=>'42','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:30'),
  array('ID'=>'43','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:32'),
  array('ID'=>'44','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:33'),
  array('ID'=>'45','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:35'),
  array('ID'=>'46','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:37'),
  array('ID'=>'47','USER_ID'=>'1','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-02-11 06:14:38'),
  array('ID'=>'48','USER_ID'=>'7','PDF_ID'=>'26','DOWNLOAD_DATETIME'=>'2014-02-11 17:08:09'),
  array('ID'=>'49','USER_ID'=>'7','PDF_ID'=>'25','DOWNLOAD_DATETIME'=>'2014-02-20 09:38:50'),
  array('ID'=>'50','USER_ID'=>'7','PDF_ID'=>'32','DOWNLOAD_DATETIME'=>'2014-02-24 11:21:15'),
  array('ID'=>'51','USER_ID'=>'7','PDF_ID'=>'25','DOWNLOAD_DATETIME'=>'2014-02-24 11:21:33'),
  array('ID'=>'52','USER_ID'=>'7','PDF_ID'=>'26','DOWNLOAD_DATETIME'=>'2014-02-24 12:21:08'),
  array('ID'=>'53','USER_ID'=>'7','PDF_ID'=>'23','DOWNLOAD_DATETIME'=>'2014-02-26 17:32:55'),
  array('ID'=>'54','USER_ID'=>'7','PDF_ID'=>'43','DOWNLOAD_DATETIME'=>'2014-02-26 18:03:02'),
  array('ID'=>'55','USER_ID'=>'7','PDF_ID'=>'25','DOWNLOAD_DATETIME'=>'2014-03-05 17:28:35'),
  array('ID'=>'56','USER_ID'=>'7','PDF_ID'=>'49','DOWNLOAD_DATETIME'=>'2014-03-15 15:35:56'),
  array('ID'=>'57','USER_ID'=>'7','PDF_ID'=>'45','DOWNLOAD_DATETIME'=>'2014-03-15 15:37:41'),
  array('ID'=>'58','USER_ID'=>'7','PDF_ID'=>'43','DOWNLOAD_DATETIME'=>'2014-03-15 15:38:11'),
  array('ID'=>'59','USER_ID'=>'7','PDF_ID'=>'43','DOWNLOAD_DATETIME'=>'2014-03-15 15:38:13'),
  array('ID'=>'60','USER_ID'=>'7','PDF_ID'=>'43','DOWNLOAD_DATETIME'=>'2014-03-15 15:38:22'),
  array('ID'=>'61','USER_ID'=>'7','PDF_ID'=>'26','DOWNLOAD_DATETIME'=>'2014-03-15 15:38:55'),
  array('ID'=>'62','USER_ID'=>'7','PDF_ID'=>'42','DOWNLOAD_DATETIME'=>'2014-03-15 15:39:51'),
  array('ID'=>'63','USER_ID'=>'7','PDF_ID'=>'36','DOWNLOAD_DATETIME'=>'2014-03-15 15:45:22'),
  array('ID'=>'64','USER_ID'=>'7','PDF_ID'=>'25','DOWNLOAD_DATETIME'=>'2014-03-15 15:47:54'),
  array('ID'=>'65','USER_ID'=>'7','PDF_ID'=>'25','DOWNLOAD_DATETIME'=>'2014-03-15 15:47:56'),
  array('ID'=>'66','USER_ID'=>'1','PDF_ID'=>'50','DOWNLOAD_DATETIME'=>'2014-03-18 11:59:54'),
  array('ID'=>'67','USER_ID'=>'1','PDF_ID'=>'46','DOWNLOAD_DATETIME'=>'2014-03-18 12:00:10'),
  array('ID'=>'68','USER_ID'=>'1','PDF_ID'=>'46','DOWNLOAD_DATETIME'=>'2014-03-18 12:00:39'),
  array('ID'=>'69','USER_ID'=>'1','PDF_ID'=>'50','DOWNLOAD_DATETIME'=>'2014-03-18 12:00:46'),
  array('ID'=>'70','USER_ID'=>'1','PDF_ID'=>'50','DOWNLOAD_DATETIME'=>'2014-03-18 12:01:18'),
  array('ID'=>'71','USER_ID'=>'1','PDF_ID'=>'50','DOWNLOAD_DATETIME'=>'2014-03-18 12:04:07')
);

// mckansys.GROUP_LV1
$GROUP_LV1 = array(
  array('ID'=>'1','NAME'=>'Think Tank','DESCRIPTION'=>'')
);

// mckansys.GROUP_LV2
$GROUP_LV2 = array(
  array('ID'=>'1','NAME'=>'Market','GROUP_LV1_ID'=>'1','DESCRIPTION'=>'Thailand Market Outlook'),
  array('ID'=>'2','NAME'=>'Knowledge','GROUP_LV1_ID'=>'1','DESCRIPTION'=>''),
  array('ID'=>'3','NAME'=>'Strategy','GROUP_LV1_ID'=>'1','DESCRIPTION'=>''),
  array('ID'=>'4','NAME'=>'Around ASEAN','GROUP_LV1_ID'=>'1','DESCRIPTION'=>'')
);

// mckansys.GROUP_LV3
$GROUP_LV3 = array(
  array('ID'=>'11','NAME'=>'Country Profile','GROUP_LV2_ID'=>'4','DESCRIPTION'=>'รวบรวมข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ รวมทั้งจุดอ่อนจุดแข็งและการคาดการณ์ถึงอนาคตอันใกล้ของแต่ละประเทศในอาเซียน'),
  array('ID'=>'15','NAME'=>'ICT Market','GROUP_LV2_ID'=>'1','DESCRIPTION'=>'อัพเดทเรื่องราวเกี่ยวกับตลาด ICT ในเมืองไทย'),
  array('ID'=>'16','NAME'=>'TechTrend Report','GROUP_LV2_ID'=>'1','DESCRIPTION'=>'เทรนด์ของเทคโนโลยีที่น่าจับตามอง')
);

);

);

);

// mckansys.INDUSTRY
$INDUSTRY = array(
  array('ID'=>'1','NAME'=>'A')
);

// mckansys.INFO
$INFO = array(
  array('ID'=>'1','LOGIN_DESCRIPTION'=>'','DESCRIPTION'=>'welcome to mckansys.. ยินดีต้อนรับสู่ Omni Knowledge Portal ','DETAIL'=>'รายละเอียดหน้าแรก','UPDATE'=>'2013-11-11 00:00:00'),
  array('ID'=>'2','LOGIN_DESCRIPTION'=>'','DESCRIPTION'=>'Please <a href="http://portal.mckansys.com/login.php">sign in</a> to download','DETAIL'=>'หัวข้อใน download box','UPDATE'=>'2013-11-18 00:00:00'),
  array('ID'=>'3','LOGIN_DESCRIPTION'=>'','DESCRIPTION'=>'or <a href="http://portal.mckansys.com/contact-us.php">contact us</a> to be a membership','DETAIL'=>'รายละเอียดใน download box','UPDATE'=>'2013-11-18 00:00:00')
);

// mckansys.JOB_LEVEL
$JOB_LEVEL = array(
  array('ID'=>'1','NAME'=>'A')
);

// mckansys.PDF
$PDF = array(
  array('ID'=>'23','NAME'=>'แนวโน้ม Near Field Communication ในประเทศไทย','PHOTO_NAME'=>'1391377563_1_CoverNFC.jpg','DESCRIPTION'=>'มัคคานซิสเชื่อว่า ภายในปี 2557  Near Field Communication (NFC) ซึ่งเป็นเทคโนโลยีการสื่อสารระยะสั้น จะเป็นช่วงเวลาแห่งการเติบโตและการใช้งานจริงอย่างแพร่หลายกับตลาดผู้บริโภคในประเทศไทย','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-02-03 04:46:03','COMPANY_ID'=>NULL,'PATH'=>'1_Tech-NFC-271013_FINAL-Cover2.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'24','NAME'=>'ทิศทาง OTT โมเดลในประเทศไทย','PHOTO_NAME'=>'2_CoverOTT.jpg','DESCRIPTION'=>'ทิศทางรูปแบบธุรกิจ OTT หรือ Over-The-Top ที่กำลังเกิดขึ้นและได้รับความนิยมในปัจจุบันจากผู้พัฒนาโมบายแอพพลิเคชั่น และส่งผลกระทบโดยตรงต่อผู้ให้บริการสื่อสารข้อมูลไร้สายทั่วโลก','BY'=>'Mckansys','PRICE'=>NULL,'UPDATE_DATE'=>'2013-12-05 00:00:00','COMPANY_ID'=>NULL,'PATH'=>'2_OTT_Complete_Cover.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'25','NAME'=>'การบูรณาการองค์กรด้วย Business Intelligence','PHOTO_NAME'=>'1391377295_3_CoverBI.jpg','DESCRIPTION'=>'Business Intelligence (BI) คือ เทคโนโลยีในรูปแบบซอฟแวร์ เป็นระบบที่ถูกนำมาใช้เพื่อวิเคราะห์ข้อมูลในการปรับปรุงการบริการและผลิตภัณฑ์ รวมทั้งกลยุทธ์ในการเปิดตลาดใหม่ๆเป็นอันดับต้นๆใน 4-5 ปีมานี้ ','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-02-03 04:41:35','COMPANY_ID'=>NULL,'PATH'=>'3_BusinessIntelligence-yah-cover.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'26','NAME'=>'ภาพรวมการสื่อสารโทรคมนาคม 2556','PHOTO_NAME'=>'1391377445_4_CoverOverall.jpg','DESCRIPTION'=>'ภาพรวมของสถานการณ์เศรษฐกิจภายในประเทศตั้งแต่ช่วงต้นปี 2555 เป็นต้นมา อุตสาหกรรมการสื่อสารโทรคมนาคมอยู่ในทิศทางที่ดีขึ้นอย่างต่อเนื่อง ความต้องการใช้บริการทางการสื่อสารมีการเติบโตอย่างชัดเจน   ','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-02-03 04:44:06','COMPANY_ID'=>NULL,'PATH'=>'4_TelecomOVERALL2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'27','NAME'=>'ภาพรวมกลุ่มบริการเสียงแบบไร้สาย (Mobile services) 2556 ','PHOTO_NAME'=>'5_CoverMobile.jpg','DESCRIPTION'=>'การเติบโตของการใช้งานโทรศัพท์เคลื่อนที่ในประเทศไทยนั้น เริ่มจากการใช้บริการเสียงที่มีโปรโมชั่นแข่งขันกันอย่างหลากหลาย ตั้งแต่ปี 2553 เป็นต้นเริ่มมีกระแสนิยมในการใช้โทรศัพท์เคลื่อนที่แบบสมาร์ทโฟนในประเทศไทยมากขึ้น','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-04 21:22:53','COMPANY_ID'=>NULL,'PATH'=>'5_TelcomVoice2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'28','NAME'=>'ภาพรวมกลุ่มบริการเสียงพื้นฐาน (Fixed-voice services) 2556 ','PHOTO_NAME'=>'6_CoverFixed.jpg','DESCRIPTION'=>'กลุ่มบริการเสียงพื้นฐานเงียบเหงามามากกว่า 5 ปี หลังจากโทรศัพท์เคลื่อนที่ได้เข้ามาแทนที่และได้รับความนิยมอย่างต่อเนื่อง  การลดลงที่เห็นผลกระทบได้ชัดเจนนั้น เพิ่งจะเกิดขึ้นในช่วงปี 2553  เนื่องจากความสามารถของบริการโทรศัพท์เคลื่อนที่และบริการอินเทอร์เน็ตความเร็วสูงเข้ามามีบทบาทและได้รับความนิยมมากขึ้นในประเทศไทย','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-04 21:22:43','COMPANY_ID'=>NULL,'PATH'=>'6_TelecomMobile2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'29','NAME'=>'ภาพรวมสถานการณ์กลุ่มสื่อสารข้อมูล (Data Services) 2556 ','PHOTO_NAME'=>'7_CoverData.jpg','DESCRIPTION'=>'ตลอดช่วงระยะเวลาในปี 2554-2555 ที่ผ่านมา กลุ่มบริการสื่อสารข้อมูลได้ถูกขับเคลื่อนการใช้งานจาก ผู้ให้บริการโทรศัพท์เคลื่อนที่, กลุ่มการเงินธนาคาร และกลุ่มขายปลีก-ส่ง เพราะผู้ใช้บริการกลุ่มนี้ได้มีการขยายพื้นที่การให้บริการและสาขาไปยังตามชุมชนต่างจังหวัดมากขึ้น ','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-04 21:17:44','COMPANY_ID'=>NULL,'PATH'=>'7_TelecomData2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'30','NAME'=>'Country Profile - Brunei','PHOTO_NAME'=>'1388460638_brunei.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศบรูไน','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-07 06:25:50','COMPANY_ID'=>NULL,'PATH'=>'1389050725_CountryProfile-Brunei2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'31','NAME'=>'Country Profile - Cambodia','PHOTO_NAME'=>'1388838551_cambodia.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศกัมพูชา','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-04 22:32:13','COMPANY_ID'=>NULL,'PATH'=>'1388849533_CountryProfile-Cambodia2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'32','NAME'=>'Country Profile - Indonesia','PHOTO_NAME'=>'1388838542_indonesia.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศอินโดนีเซีย','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-24 15:11:15','COMPANY_ID'=>NULL,'PATH'=>'1390551075_CountryProfile-Indonesia2014.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'33','NAME'=>'Country Profile - Laos','PHOTO_NAME'=>'1388838534_lao.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศลาว','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-04 22:31:03','COMPANY_ID'=>NULL,'PATH'=>'1388849463_CountryProfile-Laos2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'34','NAME'=>'Country Profile - Malaysia','PHOTO_NAME'=>'1388838524_malaysia.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศมาเลเซีย','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-04 22:30:39','COMPANY_ID'=>NULL,'PATH'=>'1388849439_CountryProfile-Malaysia2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'36','NAME'=>'Country Profile - Myanmar','PHOTO_NAME'=>'1388838507_myanmar.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศพม่า','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-24 15:15:37','COMPANY_ID'=>NULL,'PATH'=>'1390551337_CountryProfile-Myanmar2014.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'37','NAME'=>'Country Profile - Philippines','PHOTO_NAME'=>'1388838497_philipine.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศฟิลิปปินส์','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-04 22:29:30','COMPANY_ID'=>NULL,'PATH'=>'1388849370_CountryProfile-Philippines2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'38','NAME'=>'Country Profile - Singapore','PHOTO_NAME'=>'1388838485_singapore.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศสิงคโปร์','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-07 06:26:19','COMPANY_ID'=>NULL,'PATH'=>'1389050695_CountryProfile-Singapore2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'39','NAME'=>'Country Profile - Vietnam','PHOTO_NAME'=>'1389216425_vietnam.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ และ Outlook ประเทศเวียดนาม','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-09 04:27:05','COMPANY_ID'=>NULL,'PATH'=>'1388849318_CountryProfile-Vietnam2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'42','NAME'=>'Country Profile - Thailand','PHOTO_NAME'=>'1389216389_thailand.jpg','DESCRIPTION'=>'ข้อมูลพื้นฐาน ตัวเลขเศรษฐกิจ ประเทศไทย','BY'=>'Mckansys','PRICE'=>'100','UPDATE_DATE'=>'2014-01-09 04:26:29','COMPANY_ID'=>NULL,'PATH'=>'1388849023_CountryProfile-Thailand2013.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'43','NAME'=>'ความเคลื่อนไหวของพรบ.คอมพิวเตอร์','PHOTO_NAME'=>'1391375544_18_PRB.jpg','DESCRIPTION'=>'จากการสำรวจตลาดของการใช้คอมพิวเตอร์และอุปกรณ์สื่อสารโทรคมนาคมของประเทศไทยเมื่อปี 2550 ของสำนักงานสถิติแห่งชาติ กระทรวงเทคโนโลยีสารสนเทศและการสื่อสาร(ไอซีที) พบว่า มีผู้ใช้งานคอมพิวเตอร์ทุกประเภทประมาณ 16 ล้านคน(ตั้งแต่อายุ 6 ปีขึ้นไป) หรือ ร้อยละ 26.8 ของประชากรทั้งหมด โดยมีการเพิ่มการใช้งานขึ้นร้อยละ 4 เมื่อเทียบกับปี 2549 ','BY'=>'','PRICE'=>'100','UPDATE_DATE'=>'2014-02-03 04:13:09','COMPANY_ID'=>NULL,'PATH'=>'1391375544_18_ComputerCrimesThailand.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'45','NAME'=>'แนวโน้มการใช้งาน IaaS ในประเทศไทย','PHOTO_NAME'=>'1391375844_19_IaaS.jpg','DESCRIPTION'=>'IaaS หรือ infrastructure as a service เกิดเนื่องมาจากความเป็นจริงที่ว่า การลงทุนใน infrastructure นั้นใช้เงินลงทุนค่อนข้างสูง ทั้งค่าอุปกรณ์และค่าดูแลรักษาระบบ นอกจากนี้ยังพบว่าเจ้าของระบบเองก็ไม่ได้ใช้งานอย่างเต็มประสิทธิภาพเทียบกับเงินที่ลงทุนไป และการขยายการใช้งานก็ต้องใช้เงินลงทุนเพิ่มค่อนข้างสูง จึงเกิดแนวความคิดจากผู้ที่มีระบบอยู่ในมือว่า จะทำอย่างไรให้ใช้ประโยชน์จากสิ่งที่ลงทุนไปแล้วให้ได้ประโยชน์สูงที่สุด? IaaS จึงถือกำเนิดขึ้น โดยการนำระบบส่วนที่ยังไม่ได้ใช้งานไปจัดสรรให้แก่ผู้ที่ไม่มีเงินทุนเพียงพอเช่าใช้','BY'=>'','PRICE'=>'100','UPDATE_DATE'=>'2014-02-03 04:17:24','COMPANY_ID'=>NULL,'PATH'=>'1391375704_19_IaaS_TrendinThailand.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'46','NAME'=>'การประเมินมูลค่าทรัพย์สินทางปัญญา','PHOTO_NAME'=>'1391376046_20_IPV.jpg','DESCRIPTION'=>'การประเมินทรัพย์สินทางปัญญาเกิดขึ้นเนื่องจากการทำธุรกรรมซื้อ/ขายสินทรัพย์ โดยมีวัตถุประสงค์เพื่อให้ทั้งผู้ซื้อและผู้ขายรู้มูลค่าของสินทรัพย์ที่แท้จริงก่อนจะมีการตกลงซื้อหรือขายกัน','BY'=>'','PRICE'=>'100','UPDATE_DATE'=>'2014-02-03 04:38:45','COMPANY_ID'=>NULL,'PATH'=>'1391375949_20_IntellectualPropertyValuation.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'47','NAME'=>'Dynamic Consumption Behavior','PHOTO_NAME'=>'1391376199_21_DCB.jpg','DESCRIPTION'=>'Dynamic Consumption Behavior หรือการเปลี่ยนแปลงในแนวโน้มพฤติกรรมกลุ่มผู้บริโภค ถือเป็นการพลิกฟื้นคืนชีพของธุรกิจไอซีทีแบบครบวงจร (ICT Ecosystem) ตั้งแต่ผู้ให้บริการ content, platform, infrastructure ไปจนถึงผู้ผลิตอุปกรณ์และชิ้นส่วน ตลอดจนผู้ให้บริการประเภท system integration และ managed services ','BY'=>'','PRICE'=>'100','UPDATE_DATE'=>'2014-02-03 04:23:37','COMPANY_ID'=>NULL,'PATH'=>'1391376199_21_DynamicConsumptionBehavior.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'48','NAME'=>'เทรนด์ธุรกิจยุคดิจิตัล 2557','PHOTO_NAME'=>'1391377050_22_BusinessTrend.jpg','DESCRIPTION'=>'จากการสำรวจเทรนด์ในองค์กรยุคดิจิตัล ที่ต้องจับตาในปี 2557 พบว่า มี 4 เรื่องหลักที่เกี่ยวข้องกับการพัฒนาวิสัยทัศน์ขององค์กร ','BY'=>'','PRICE'=>'100','UPDATE_DATE'=>'2014-02-03 04:37:30','COMPANY_ID'=>NULL,'PATH'=>'1391377050_22_TrendBusinessDigitalAge.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'49','NAME'=>'เทรนด์การใช้งาน Smart Device','PHOTO_NAME'=>'1391987825_22_SmartDeviceTrend.jpg','DESCRIPTION'=>'มัคคานซิส เผยผลการศึกษาผู้ใช้งานสมาร์ทดีไวซ์เกินครึ่ง ถือครองมากกว่า 1 เครื่องในเวลาเดียวกัน ส่งผลดีต่อการเติบโตของปริมาณการใช้งานดาต้า','BY'=>'','PRICE'=>'100','UPDATE_DATE'=>'2014-02-10 06:18:22','COMPANY_ID'=>NULL,'PATH'=>'1391987825_23_SmartDeviceUsage.pdf','Is_Asian_country'=>'0'),
  array('ID'=>'50','NAME'=>'The New Chapter of Customer Relation Management','PHOTO_NAME'=>'1395118867_CoverCRM.jpg','DESCRIPTION'=>'ในปัจจุบัน ช่องทางการสื่อสารระหว่างบริษัทและลูกค้ามีอยู่หลากหลายช่องทาง ซึ่งข้อมูลต่างๆของลูกค้าแพร่กระจายอยู่่ในทุกช่องทาง การดึงข้อมูลเหล่านั้นมาใช้ให้เกิดประโยชน์สูงสุดได้ นับเป็นสิ่งจำเป็นเพื่อให้บริษัทเข้าถึงความต้องการของลูกค้า โดยเครื่องมือเหล่านี้ Customer Data Management (CDM), Personalization และ Contextualization มีบทบาทสำคัญที่จะในการนำข้อมูลมาวิเคราะห์ และพิจารณาเพื่อกำหนดแผนงานดำเนินงานของบริษัทต่อไป','BY'=>'','PRICE'=>'100','UPDATE_DATE'=>'2014-03-18 12:01:07','COMPANY_ID'=>NULL,'PATH'=>'1395118401_New_Chapter_CRM_032014.pdf','Is_Asian_country'=>'0')
);

// mckansys.PDF_CATEGORY
$PDF_CATEGORY = array(
  array('ID'=>'37','PDF_ID'=>'23','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'16'),
  array('ID'=>'38','PDF_ID'=>'24','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'16'),
  array('ID'=>'39','PDF_ID'=>'25','GROUP_LEVEL_NAME'=>'2','GROUP_LEVEL_ID'=>'3'),
  array('ID'=>'40','PDF_ID'=>'26','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'15'),
  array('ID'=>'41','PDF_ID'=>'27','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'15'),
  array('ID'=>'42','PDF_ID'=>'28','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'15'),
  array('ID'=>'43','PDF_ID'=>'29','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'15'),
  array('ID'=>'44','PDF_ID'=>'30','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'45','PDF_ID'=>'31','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'46','PDF_ID'=>'32','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'47','PDF_ID'=>'33','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'48','PDF_ID'=>'34','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'50','PDF_ID'=>'36','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'51','PDF_ID'=>'37','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'52','PDF_ID'=>'38','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'53','PDF_ID'=>'39','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'56','PDF_ID'=>'42','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'11'),
  array('ID'=>'57','PDF_ID'=>'43','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'15'),
  array('ID'=>'59','PDF_ID'=>'45','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'16'),
  array('ID'=>'60','PDF_ID'=>'46','GROUP_LEVEL_NAME'=>'2','GROUP_LEVEL_ID'=>'2'),
  array('ID'=>'61','PDF_ID'=>'47','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'16'),
  array('ID'=>'62','PDF_ID'=>'48','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'16'),
  array('ID'=>'63','PDF_ID'=>'49','GROUP_LEVEL_NAME'=>'3','GROUP_LEVEL_ID'=>'15'),
  array('ID'=>'64','PDF_ID'=>'50','GROUP_LEVEL_NAME'=>'2','GROUP_LEVEL_ID'=>'2')
);

// mckansys.PERMISSION
$PERMISSION = array(
  array('ID'=>'1','USER_PROFILE_ID'=>'1','GROUP_LV2_ID'=>'2','IS_ACTIVE'=>'Y','START_DATE'=>'2013-09-01 00:00:00','END_DATE'=>'2014-09-28 00:00:00'),
  array('ID'=>'2','USER_PROFILE_ID'=>'3','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2013-10-03 00:00:00','END_DATE'=>'2014-10-17 00:00:00'),
  array('ID'=>'3','USER_PROFILE_ID'=>'4','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2013-09-01 00:00:00','END_DATE'=>'2014-09-28 00:00:00'),
  array('ID'=>'4','USER_PROFILE_ID'=>'4','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'N','START_DATE'=>'2013-01-01 00:00:00','END_DATE'=>'2013-01-01 00:00:00'),
  array('ID'=>'5','USER_PROFILE_ID'=>'3','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'N','START_DATE'=>'2013-10-01 00:00:00','END_DATE'=>'2013-10-01 00:00:00'),
  array('ID'=>'6','USER_PROFILE_ID'=>'1','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2013-10-17 00:00:00','END_DATE'=>'2014-10-31 00:00:00'),
  array('ID'=>'7','USER_PROFILE_ID'=>'1','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'Y','START_DATE'=>'1970-01-01 00:00:00','END_DATE'=>'2014-12-31 00:00:00'),
  array('ID'=>'8','USER_PROFILE_ID'=>'3','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'N','START_DATE'=>'2013-11-05 00:00:00','END_DATE'=>'2013-11-30 00:00:00'),
  array('ID'=>'9','USER_PROFILE_ID'=>'3','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'N','START_DATE'=>'2013-11-05 00:00:00','END_DATE'=>'2013-11-30 00:00:00'),
  array('ID'=>'10','USER_PROFILE_ID'=>'7','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'11','USER_PROFILE_ID'=>'7','GROUP_LV2_ID'=>'2','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'12','USER_PROFILE_ID'=>'7','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'13','USER_PROFILE_ID'=>'7','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'14','USER_PROFILE_ID'=>'9','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'15','USER_PROFILE_ID'=>'9','GROUP_LV2_ID'=>'2','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'16','USER_PROFILE_ID'=>'9','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'17','USER_PROFILE_ID'=>'9','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'18','USER_PROFILE_ID'=>'10','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'19','USER_PROFILE_ID'=>'10','GROUP_LV2_ID'=>'2','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'20','USER_PROFILE_ID'=>'10','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'21','USER_PROFILE_ID'=>'10','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'22','USER_PROFILE_ID'=>'11','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'23','USER_PROFILE_ID'=>'11','GROUP_LV2_ID'=>'2','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'24','USER_PROFILE_ID'=>'11','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'25','USER_PROFILE_ID'=>'11','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'26','USER_PROFILE_ID'=>'12','GROUP_LV2_ID'=>'2','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'27','USER_PROFILE_ID'=>'12','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'28','USER_PROFILE_ID'=>'12','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'29','USER_PROFILE_ID'=>'12','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'30','USER_PROFILE_ID'=>'13','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'31','USER_PROFILE_ID'=>'13','GROUP_LV2_ID'=>'2','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'32','USER_PROFILE_ID'=>'13','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'33','USER_PROFILE_ID'=>'13','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'34','USER_PROFILE_ID'=>'14','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'35','USER_PROFILE_ID'=>'14','GROUP_LV2_ID'=>'2','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'36','USER_PROFILE_ID'=>'14','GROUP_LV2_ID'=>'3','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'37','USER_PROFILE_ID'=>'14','GROUP_LV2_ID'=>'4','IS_ACTIVE'=>'Y','START_DATE'=>'2014-01-01 00:00:00','END_DATE'=>'2014-06-30 00:00:00'),
  array('ID'=>'38','USER_PROFILE_ID'=>'1','GROUP_LV2_ID'=>'1','IS_ACTIVE'=>'Y','START_DATE'=>'2014-02-03 00:00:00','END_DATE'=>'2014-07-31 00:00:00')
);

// mckansys.QUESTION
$QUESTION = array(
  array('ID'=>'1','NAME'=>'What was your childhood nickname?'),
  array('ID'=>'2','NAME'=>'What is the name of your favorite childhood friend? '),
  array('ID'=>'3','NAME'=>'What is the middle name of your oldest child?'),
  array('ID'=>'4','NAME'=>'What school did you attend for sixth grade?'),
  array('ID'=>'5','NAME'=>'What was the name of your first stuffed animal?'),
  array('ID'=>'6','NAME'=>'In what city or town did your mother and father meet? '),
  array('ID'=>'7','NAME'=>'In what city does your nearest sibling live? '),
  array('ID'=>'8','NAME'=>'In what city or town was your first job?'),
  array('ID'=>'9','NAME'=>'What is the name of the place your wedding reception was held?'),
  array('ID'=>'10','NAME'=>'What was your favorite place to visit as a child?'),
  array('ID'=>'11','NAME'=>'What is the street number of the house you grew up in?'),
  array('ID'=>'12','NAME'=>'What was your dream job as a child? ')
);

// mckansys.TAG
$TAG = array(
  array('ID'=>'1','NAME'=>'tag1'),
  array('ID'=>'2','NAME'=>'tag2'),
  array('ID'=>'3','NAME'=>'tag3'),
  array('ID'=>'4','NAME'=>'tag4'),
  array('ID'=>'5','NAME'=>'tag5'),
  array('ID'=>'6','NAME'=>'')
);

// mckansys.TAG_RELATIONSHIP
$TAG_RELATIONSHIP = array(
  array('PDF_ID'=>'23','TAG_ID'=>'6'),
  array('PDF_ID'=>'25','TAG_ID'=>'6'),
  array('PDF_ID'=>'26','TAG_ID'=>'6'),
  array('PDF_ID'=>'27','TAG_ID'=>'6'),
  array('PDF_ID'=>'28','TAG_ID'=>'6'),
  array('PDF_ID'=>'29','TAG_ID'=>'6'),
  array('PDF_ID'=>'30','TAG_ID'=>'6'),
  array('PDF_ID'=>'31','TAG_ID'=>'6'),
  array('PDF_ID'=>'32','TAG_ID'=>'6'),
  array('PDF_ID'=>'33','TAG_ID'=>'6'),
  array('PDF_ID'=>'34','TAG_ID'=>'6'),
  array('PDF_ID'=>'36','TAG_ID'=>'6'),
  array('PDF_ID'=>'37','TAG_ID'=>'6'),
  array('PDF_ID'=>'38','TAG_ID'=>'6'),
  array('PDF_ID'=>'39','TAG_ID'=>'6'),
  array('PDF_ID'=>'42','TAG_ID'=>'6'),
  array('PDF_ID'=>'43','TAG_ID'=>'6'),
  array('PDF_ID'=>'45','TAG_ID'=>'6'),
  array('PDF_ID'=>'46','TAG_ID'=>'6'),
  array('PDF_ID'=>'47','TAG_ID'=>'6'),
  array('PDF_ID'=>'49','TAG_ID'=>'6'),
  array('PDF_ID'=>'50','TAG_ID'=>'6')
);

// mckansys.TECHNOLOGY_ID
$TECHNOLOGY_ID = array(
  array('ID'=>'1','NAME'=>'A')
);

);

// mckansys.USER_PROFILE
$USER_PROFILE = array(
  array('ID'=>'1','FIRSTNAME'=>'sukanya','LASTNAME'=>'AA','EMAIL'=>'a@a.com','COMPANY'=>'AA','PASSWORD'=>'f51fc62cdba8a6e536d604b47e30b49551c560256dac08ccfc8204823a492775d669a57e','JOB_TITLE'=>'test','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'Y','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'221','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'testUserProfile.jpg','QUESTION_ID'=>'1','ANSWER'=>'a'),
  array('ID'=>'3','FIRSTNAME'=>'B','LASTNAME'=>'B','EMAIL'=>'nikom2532@gmail.com','COMPANY'=>'B','PASSWORD'=>'7014de06693eca5c7a6f258b98fa2048ef7ad6c1faf1e46a706cd0615ada442bbc570b0e','JOB_TITLE'=>'','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'Y','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'1','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'','QUESTION_ID'=>'2','ANSWER'=>'b'),
  array('ID'=>'4','FIRSTNAME'=>'Voravan','LASTNAME'=>'Charn','EMAIL'=>'wc.fone@yahoo.com','COMPANY'=>'Buildthedot','PASSWORD'=>'7014de06693eca5c7a6f258b98fa2048ef7ad6c1faf1e46a706cd0615ada442bbc570b0e','JOB_TITLE'=>NULL,'ADDRESS'=>NULL,'CITY'=>NULL,'ZIP'=>NULL,'PHONE'=>NULL,'FAX'=>NULL,'IS_ACTIVE'=>'Y','IS_ADMIN'=>'Y','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'1','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'','QUESTION_ID'=>'3','ANSWER'=>'fon'),
  array('ID'=>'7','FIRSTNAME'=>'Yuthana','LASTNAME'=>'Siri','EMAIL'=>'yuthana@mckansys.com','COMPANY'=>'Mckansys (Thailand) Co., Ltd.','PASSWORD'=>'f51fc62cdba8a6e536d604b47e30b49551c560256dac08ccfc8204823a492775d669a57e','JOB_TITLE'=>'','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'Y','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'221','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'no-image.png','QUESTION_ID'=>'0','ANSWER'=>''),
  array('ID'=>'9','FIRSTNAME'=>'Warunee','LASTNAME'=>'P','EMAIL'=>'warunee.p@oto.samartcorp.com','COMPANY'=>'One to One Contact Center','PASSWORD'=>'48ee13603e6787fcb67f822b3ea35835cbfeef0cf18bfcb92f1fe02755b61c3112c7bbcd','JOB_TITLE'=>'','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'N','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'221','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'no-image.png','QUESTION_ID'=>'0','ANSWER'=>''),
  array('ID'=>'10','FIRSTNAME'=>'Yugijo','LASTNAME'=>'D','EMAIL'=>'Yugijo.d@aapico.com','COMPANY'=>'Aapica','PASSWORD'=>'fdd6a13634952d950883fd6d4e40274f94836ddcda485e1e19f409322e0da43066fabd13','JOB_TITLE'=>'','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'N','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'221','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'no-image.png','QUESTION_ID'=>'0','ANSWER'=>''),
  array('ID'=>'11','FIRSTNAME'=>'Siribhorn','LASTNAME'=>'','EMAIL'=>'siribhorn@etda.or.th','COMPANY'=>'ETDA','PASSWORD'=>'9519950266969f700abfbe7ae55a1bd188736b4a7919bc0543ba54e39a4624d125665f0d','JOB_TITLE'=>'','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'N','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'221','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'no-image.png','QUESTION_ID'=>'0','ANSWER'=>''),
  array('ID'=>'12','FIRSTNAME'=>'Thaveesak','LASTNAME'=>'D','EMAIL'=>'thaveesak.d@irpc.co.th','COMPANY'=>'IRPC','PASSWORD'=>'1210fe92ce4d4ab06b68c9750907dc4fcd08b85bb85beecfec9094b601a7edad8260da27','JOB_TITLE'=>'','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'N','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'221','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'no-image.png','QUESTION_ID'=>'0','ANSWER'=>''),
  array('ID'=>'13','FIRSTNAME'=>'Panida','LASTNAME'=>'w','EMAIL'=>'panidaw@scg.co.th','COMPANY'=>'SCG','PASSWORD'=>'98cd8e68c6d6c00b35d721f1a71bb086ffdac90d66558bc8b9d7566d1f761aa52960ce42','JOB_TITLE'=>'','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'N','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'221','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'no-image.png','QUESTION_ID'=>'0','ANSWER'=>''),
  array('ID'=>'14','FIRSTNAME'=>'Thanit','LASTNAME'=>'Sor','EMAIL'=>'thanit_sor@truecorp.co.th','COMPANY'=>'True Coporation','PASSWORD'=>'a9d05e92dad95b06c12fca58a0ab921b241c87ee7c2458ccba77fc9f030ea97bb526d911','JOB_TITLE'=>'','ADDRESS'=>'','CITY'=>'','ZIP'=>'','PHONE'=>'','FAX'=>'','IS_ACTIVE'=>'Y','IS_ADMIN'=>'N','JOB_LEVEL'=>'1','DEPARTMENT_ID'=>'1','INDUSTRY_ID'=>'1','COUNTRY_ID'=>'221','TECHNOLOGY_ID'=>'1','USER_PROFILEcol'=>NULL,'PHOTO_NAME'=>'no-image.png','QUESTION_ID'=>'0','ANSWER'=>'')
);

);
